name: Automated Build for Gateways App (Musala Soft)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Installing dependencies and running tests
      run: |
        npm install
        npm run test
      env:
        CI: true
